[
  {
    "photo":"img/joueur/kwiz.jpg",
    "name":"kwiz",
    "reroll":"img/class/fury.png",
    "reroll2":"img/class/rogue.jpg",
    "email":"500k",
    "reroll3":"img/gold.png",
    "phone":"0646129839",
    "web":"null"
  },
  {
    "photo":"img/joueur/zahya.jpg",
    "name":"zahya",
    "reroll":"img/class/demo.png",
    "reroll2":"img/class/mage.png",
    "email":"carladoe@site.com",
    "reroll3":"img/gold.png",
    "phone":"1-333-111-555",
    "web":"http://carladoe.com"
  },
  {
    "photo":"img/joueur/shadow.jpg",
    "name":"Shadowstorm",
    "reroll":"img/class/fury.png",
    "reroll2":"img/class/rogue.jpg",
    "email":"stefano@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-444-222-777",
    "web":"http://stefano.com"
  },
  {
    "photo":"img/joueur/liam.jpg",
    "name":"Liam",
    "reroll":"img/class/rdrood.png",
    "reroll2":"img/class/hpal.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/xigo.jpg",
    "name":"Xigo",
    "reroll":"img/class/fury.png",
    "reroll2":"img/class/mage.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/ixie.jpg",
    "name":"Ixie",
    "reroll":"img/class/ret.png",
    "reroll2":"img/class/amelio.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/princou.jpg",
    "name":"Princou",
    "reroll":"img/class/dk.png",
    "reroll2":"img/class/ret.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/veli.jpg",
    "name":"Velistraz",
    "reroll":"img/class/amelio.png",
    "reroll2":"img/class/mage.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/echo.jpg",
    "name":"Echoes",
    "reroll":"img/class/rdrood.png",
    "reroll2":"img/class/disci.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/cancer.jpg",
    "name":"Cancerologue",
    "reroll":"img/class/rogue.jpg",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/sere.jpg",
    "name":"Serenity",
    "reroll":"img/class/rogue.jpg",
    "reroll2":"img/class/dk.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/crash.jpg",
    "name":"Crashley",
    "reroll":"img/class/mage.png",
    "reroll2":"img/class/hunt.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/nyluka.jpg",
    "name":"Nyluka",
    "reroll":"img/class/hunt.png",
    "reroll2":"img/class/mage.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/elinn.jpg",
    "name":"Elinn",
    "reroll":"img/class/equi.png",
    "reroll2":"img/class/mage.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/caloue.jpg",
    "name":"Caloue",
    "reroll":"img/class/equi.png",
    "reroll2":"img/class/hunt.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/strogz.jpg",
    "name":"Strogz",
    "reroll":"img/class/demo.png",
    "reroll2":"img/class/hunt.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/shadala.jpg",
    "name":"Shadala",
    "reroll":"img/class/mage.png",
    "reroll2":"img/class/sp.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/qrsn.jpg",
    "name":"Qrsn",
    "reroll":"img/class/sp.png",
    "reroll2":"img/class/mage.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/hadvi.jpg",
    "name":"Hadvi",
    "reroll":"img/class/demo.png",
    "reroll2":"img/class/elem.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/taliau.jpg",
    "name":"Taliau",
    "reroll":"img/class/mage.png",
    "reroll2":"img/class/equi.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/fenty.jpg",
    "name":"Fenty",
    "reroll":"img/class/hunt.png",
    "reroll2":"img/class/mage.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/personn.jpg",
    "name":" Personn",
    "reroll":"img/class/rcham.png",
    "reroll2":"img/class/hmonk.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/aza.jpg",
    "name":"Azaghal",
    "reroll":"img/class/disci.png",
    "reroll2":"img/class/rcham.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/tygrou.jpg",
    "name":"Tygrou",
    "reroll":"img/class/rdrood.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/brain.jpg",
    "name":"Brainafleck",
    "reroll":"img/class/tankmonk.png",
    "reroll2":"img/class/gardian.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  },
  {
    "photo":"img/joueur/lecre.jpg",
    "name":"Lecrecia",
    "reroll":"img/class/blood.png",
    "reroll2":"img/class/prot.png",
    "email":"angeline@site.com",
    "reroll3":"img/gold.png",
    "phone":"2-555-555-555",
    "web":"http://angeline.com"
  }
]
